import pickle
import pandas as pd
from sklearn.linear_model import LinearRegression
from .models import CityCode

stateDict = {
  'Alabama':'Alabama',
  'Alaska':'Alaska',
  'Arizona':'Arizona',
  'Arkansas':'Arkansas',
  'California':'California',
  'Colorado':'Colorado',
  'Connecticut':'Connecticut',
  'Delaware':'Delaware',
  'District of Columbia':'District of Columbia',
  'Florida':'Florida',
  'Georgia':'Georgia',
  'Hawaii':'Hawaii',
  'Idaho':'Idaho',
  'Illinois':'Illinois',
  'Indiana':'Indiana',
  'Iowa':'Iowa',
  'Kansas':'Kansas',
  'Kentucky':'Kentucky',
  'Louisiana':'Louisiana',
  'Maine':'Maine',
  'Maryland':'Maryland',
  'Massachusetts':'Massachusetts',
  'Michigan':'Michigan',
  'Minnesota':'Minnesota',
  'Mississippi':'Mississippi',
  'Missouri':'Missouri',
  'Montana':'Montana',
  'Nebraska':'Nebraska',
  'Nevada':'Nevada',
  'New Hampshire':'New Hampshire',
  'New Jersey':'New Jersey',
  'New Mexico':'New Mexico',
  'New York':'New York',
  'North Carolina':'North Carolina',
  'North Dakota': 'North Dakota',
  'Ohio':'Ohio',
  'Oklahoma':'Oklahoma',
  'Oregon':'Oregon',
  'Pennsylvania':'Pennsylvania',
  'Puerto Rico':'Puerto Rico',
  'Rhode Island':'Rhode Island',
  'South Carolina':'South Carolina',
  'South Dakota':'South Dakota',
  'Tennessee':'Tennessee',
  'Texas':'Texas',
  'Utah':'Utah',
  'Vermont':'Vermont',
  'Virgin Islands':'Virgin Islands',
  'Virginia':'Virginia',
  'Washington':'Washington',
  'West Virginia':'West Virginia',
  'Wisconsin':'Wisconsin',
  'Wyoming':'Wyoming'
  }

realtorModel = pickle.load(open('../Data/realtor-model.pkl', 'rb'))

def createHouse(houseData):
  cityCode = list(CityCode.objects.filter(city=houseData['city']).values('id'))[0]['id']
  
  house = pd.DataFrame({'bed':[float(houseData['beds'])],
                         'bath':[float(houseData['baths'])],
                         'acre_lot':[float(houseData['lot'])],
                         'city': [cityCode],
                         'house_size':[float(houseData['sqft'])],
                         'Alabama':stateDict['Alabama'] == houseData['state'],
                         'Alaska':stateDict['Alaska'] == houseData['state'],
                         'Arizona':stateDict['Arizona'] == houseData['state'],
                         'Arkansas':stateDict['Arkansas'] == houseData['state'],
                         'California':stateDict['California'] == houseData['state'],
                         'Colorado':stateDict['Colorado'] == houseData['state'],
                         'Connecticut':stateDict['Connecticut'] == houseData['state'],
                         'Delaware':stateDict['Delaware'] == houseData['state'],
                         'District of Columbia':stateDict['District of Columbia'] == houseData['state'],
                         'Florida':stateDict['Florida'] == houseData['state'],
                         'Georgia':stateDict['Georgia'] == houseData['state'],
                         'Hawaii':stateDict['Hawaii'] == houseData['state'],
                         'Idaho':stateDict['Idaho'] == houseData['state'],
                         'Illinois':stateDict['Illinois'] == houseData['state'],
                         'Indiana':stateDict['Indiana'] == houseData['state'],
                         'Iowa':stateDict['Iowa'] == houseData['state'],
                         'Kansas':stateDict['Kansas'] == houseData['state'],
                         'Kentucky':stateDict['Kentucky'] == houseData['state'],
                         'Louisiana':stateDict['Louisiana'] == houseData['state'],
                         'Maine':stateDict['Maine'] == houseData['state'],
                         'Maryland':stateDict['Maryland'] == houseData['state'],
                         'Massachusetts':stateDict['Massachusetts'] == houseData['state'],
                         'Michigan':stateDict['Michigan'] == houseData['state'],
                         'Minnesota':stateDict['Minnesota'] == houseData['state'],
                         'Mississippi':stateDict['Mississippi'] == houseData['state'],
                         'Missouri':stateDict['Missouri'] == houseData['state'],
                         'Montana':stateDict['Montana'] == houseData['state'],
                         'Nebraska':stateDict['Nebraska'] == houseData['state'],
                         'Nevada':stateDict['Nevada'] == houseData['state'],
                         'New Hampshire':stateDict['New Hampshire'] == houseData['state'],
                         'New Jersey':stateDict['New Jersey'] == houseData['state'],
                         'New Mexico':stateDict['New Mexico'] == houseData['state'],
                         'New York':stateDict['New York'] == houseData['state'],
                         'North Carolina':stateDict['North Carolina'] == houseData['state'],
                         'North Dakota': stateDict['North Dakota'] == houseData['state'],
                         'Ohio':stateDict['Ohio'] == houseData['state'],
                         'Oklahoma':stateDict['Oklahoma'] == houseData['state'],
                         'Oregon':stateDict['Oregon'] == houseData['state'],
                         'Pennsylvania':stateDict['Pennsylvania'] == houseData['state'],
                         'Puerto Rico':stateDict['Puerto Rico'] == houseData['state'],
                         'Rhode Island':stateDict['Rhode Island'] == houseData['state'],
                         'South Carolina':stateDict['South Carolina'] == houseData['state'],
                         'South Dakota':stateDict['South Dakota'] == houseData['state'],
                         'Tennessee':stateDict['Tennessee'] == houseData['state'],
                         'Texas':stateDict['Texas'] == houseData['state'],
                         'Utah':stateDict['Utah'] == houseData['state'],
                         'Vermont':stateDict['Vermont'] == houseData['state'],
                         'Virgin Islands':stateDict['Virgin Islands'] == houseData['state'],
                         'Virginia':stateDict['Virginia'] == houseData['state'],
                         'Washington':stateDict['Washington'] == houseData['state'],
                         'West Virginia':stateDict['West Virginia'] == houseData['state'],
                         'Wisconsin':stateDict['Wisconsin'] == houseData['state'],
                         'Wyoming':stateDict['Wyoming'] == houseData['state']})
  return house

def estateEstimation(house):
  return realtorModel.predict(house)



