# Generated by Django 3.2.25 on 2024-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_alter_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycodes',
            name='id',
        ),
        migrations.AlterField(
            model_name='citycodes',
            name='code',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citystate',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
