# Generated by Django 3.2.25 on 2024-05-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_auto_20240512_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citycodes',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='citystate',
            old_name='state',
            new_name='state_id',
        ),
    ]
