# Generated by Django 3.2.25 on 2024-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_auto_20240512_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycodes',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citycodes',
            name='code',
            field=models.FloatField(),
        ),
    ]
