# Generated by Django 3.2.25 on 2024-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_auto_20240512_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
