# Generated by Django 3.2.25 on 2024-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_alter_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citystate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
