# Generated by Django 3.2.25 on 2024-05-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_auto_20240512_0848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityCodes',
            new_name='CityCode',
        ),
    ]
