# Generated by Django 3.2.25 on 2024-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0010_auto_20240515_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='citystate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state',
        ),
        migrations.AlterField(
            model_name='citycode',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citystate',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
